name: Build and Test
on:
 push:
   branches: [ main ]
 pull_request:
   branches: [ main ]

jobs:
 build_and_test:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v2
   - name: Set up JDK 20
     uses: actions/setup-java@v2
     with:
       java-version: '20'
   - name: Grant execute permission for gradlew
     run: chmod +x ./gradlew
   - name: Build with Gradle
     run: ./gradlew build
     working-directory: ./medalseats-deployments/medalseats-management
   - name: Test with Gradle
     run: ./gradlew test
     working-directory: ./medalseats-deployments/medalseats-management